export interface Task {
  id: number;
  description: string;
  state: boolean;
}

export interface User {
  page: number;
  isLoading: boolean;
  usersData: UserData;
}
// Generated by https://quicktype.io

export interface UserData {
  page: number;
  per_page: number;
  total: number;
  total_pages: number;
  data: Data[];
}

export interface Data {
  id: number;
  email: string;
  first_name: string;
  last_name: string;
  avatar: string;
}
